name: animated_ballot_package_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.2

environment:
  sdk: ">=2.15.1 <3.0.0" #Dart SDK 2021-12-16
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  animation_checkmark:
    path: ../
  cupertino_icons: ^1.0.4

dev_dependencies:
  test:

flutter:
  uses-material-design: true
